### ISSUE TITLE
/api/user/me is useless

### ISSUE THREAD

**Issue by jellllly420** [pkuSoftwareTeamWaterProof/forwardingQuotationPlatformBack#35]

**Comment by laolee010126** [comment]
<img width="961" alt="스크린샷 2023-12-14 오전 10 54 35" src="https://github.com/pkuSoftwareTeamWaterProof/forwardingQuotationPlatformBack/assets/67942295/7db23a60-21b1-4715-857c-7d6169bd8177">

现在此功能可以用了，提供一个token发请求，返回user信息
