### ISSUE TITLE
fix: re-organize API in one unified namespace

### ISSUE THREAD

**Issue by jellllly420** [pkuSoftwareTeamWaterProof/forwardingQuotationPlatformBack#4]
Current API route is not tidy or extensible. 

For example, we post to `/api/user/create` to create a new user, but we post to `/sheet` to create a new inquiry sheet. 

Generally I think we should stick to the manner in 0a2c3ee0a14ec1a370e06e2e3b8f42677be881d8.

**Comment by jellllly420** [comment]
The person who would work on this issue should also modify relevant parts in the frontend repo (or ping me for sync).

**Comment by shuiliunian** [comment]
okok，我会修改的

**Comment by laolee010126** [comment]
修改完成
